package de.nb.aitddadventure.domain;

/**
 * Kennung eines Raums.
 */
public enum RoomId {
  START_FOREST,
  CLEARING,
  RETURNED_FOREST,
  LARGE_STONE,
  STONE_SURFACE_CLEARING,
  RETURNED_CLEARING,
  STONE_SURFACE_RETURNED_CLEARING,
  STONE_CIRCLE,
  STONE_CIRCLE_EXIT,
  RETURNED_LARGE_STONE,
  STRANGE_FEELING,
  SWORD_IN_STONE,
  PULLED_SWORD
}
